# Generated by Django 2.1.1 on 2019-04-23 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('US Dollars', 'USD'), ('Pound sterlings', 'GBP'), ('EURO', 'EUR')], default='US Dollars', max_length=300, verbose_name='Name of the currency')),
                ('abbreviation', models.CharField(choices=[('US Dollars', 'USD'), ('Pound sterlings', 'GBP'), ('EURO', 'EUR')], default='USD', max_length=30, verbose_name='Abbreviation of the currency')),
                ('defaultSystemCurrency', models.BooleanField(default=False, verbose_name='Is a default currency of the entire system')),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyRatio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratio', models.DecimalField(decimal_places=4, default=0.0, max_digits=190, null=True, verbose_name='Ratio of linked currencies')),
                ('fromCurrency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_ratio_from_currency', to='currencies.Currency', verbose_name='First currency of the relation')),
                ('toCurrency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_ratio_to_currency', to='currencies.Currency', verbose_name='Second currency of the relation')),
            ],
        ),
    ]
