# Generated by Django 2.1.1 on 2019-04-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='abbreviation',
            field=models.CharField(default='', max_length=30, verbose_name='Abbreviation of the currency'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(choices=[('USD', 'USD'), ('GBP', 'GBP'), ('EURO', 'EURO')], default='USD', max_length=300, verbose_name='Name of the currency'),
        ),
    ]
