# Generated by Django 2.1.1 on 2019-04-23 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('currencies', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=4, default=0.0, max_digits=190, verbose_name='Value of the transaction denoted in from currency')),
                ('exchangeRate', models.DecimalField(decimal_places=4, default=0.0, max_digits=190, verbose_name='Ratio of currencies used in the transaction')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('transactionStatusChoices', models.CharField(choices=[('Pending', 'Pending'), ('Failed', 'Failed'), ('Processed', 'Processed')], default='Pending', max_length=300, verbose_name='Status of the transaction')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated at')),
                ('fromCurrency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_from_currency', to='currencies.Currency', verbose_name='From currency of the transaction')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_recipient', to='clients.Client', verbose_name='Recipient of the transaction')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_sender', to='clients.Client', verbose_name='Creator of the transaction')),
                ('toCurrency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_to_currency', to='currencies.Currency', verbose_name='Tocurrency of the transaction')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
